### ISSUE TITLE
Error reports for RegularExpression mismatches are not clear

### ISSUE THREAD

**Issue by SaidMavlyan** [gudwin/botbuilder-unit#3]
When we define Bot answers with regular expressions, we don't get clear error reports on test fails.
Following are examples with `string` and `regex` responses from bot.

Example with `string`:
```js
    { "user": "reserve meeting room on Tuesday at 3pm" },
    { "bot": "for how long" }
```
When it fails, we get clear error message, indicating which statement was not matched.
As following: 
![2017-12-12-121238_1366x768_scrot](https://user-images.githubusercontent.com/11050284/33870584-b75ac446-df38-11e7-8442-60b8f601d44a.png)

---
Example with `regex`;
```js
    { "user": "reserve meeting room on Tuesday at 3pm" },
    { "bot": /^for how long/ }
```
When it fails with regex answer, we get verbose but not useful report.
As following: 
![2017-12-12-121612_1366x768_scrot](https://user-images.githubusercontent.com/11050284/33870773-b25f4128-df39-11e7-9fe0-36346e4052d0.png)

```txt
TypeError: msg.split is not a function at BeautyLogReporter.outputMessageBox (/project/node_modules/botbuilder-unit/src/log-reporters/BeautyLogReporter.js:56:19)
at BeautyLogReporter.expectationError (/project/node_modules/botbuilder-unit/src/log-reporters/BeautyLogReporter.js:148:8)
at beforeFunc.then (/project/node_modules/botbuilder-unit/src/messages/BotMessage.js:28:34)
at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by gudwin** [comment]
Fixed in https://github.com/gudwin/botbuilder-unit/releases/tag/0.5.5

<img width="507" alt="2017-12-13 3 06 42" src="https://user-images.githubusercontent.com/3242196/33915137-c9aa1974-dfb2-11e7-9595-2f0bd4ed78f1.png">

Please, confirm the fix. 

P.S. Unfortunately, I didn't covered log reporters by tests, but will fix that soon too.

**Comment by SaidMavlyan** [comment]
@gudwin , after update to 0.5.5 version, problem is gone. Thanks!
